# Machine Learning: Classification - Managing the Quality Metric of Global Ecological Footprint 

# STAGE C

In [4]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [134]:
a=pd.read_csv('Data_for_UCI_named.csv')

In [135]:
a.head()

,tau1,tau2,tau3,tau4,p1,p2,p3,p4,g1,g2,g3,g4,stab,stabf
0,2.959060,3.079885,8.381025,9.780754,3.763085,-0.782604,-1.257395,-1.723086,0.650456,0.859578,0.887445,0.958034,0.055347,unstable
1,9.304097,4.902524,3.047541,1.369357,5.067812,-1.940058,-1.872742,-1.255012,0.413441,0.862414,0.562139,0.781760,-0.005957,stable
2,8.971707,8.848428,3.046479,1.214518,3.405158,-1.207456,-1.277210,-0.920492,0.163041,0.766689,0.839444,0.109853,0.003471,unstable
3,0.716415,7.669600,4.486641,2.340563,3.963791,-1.027473,-1.938944,-0.997374,0.446209,0.976744,0.929381,0.362718,0.028871,unstable
4,3.134112,7.608772,4.943759,9.857573,3.525811,-1.125531,-1.845975,-0.554305,0.797110,0.455450,0.656947,0.820923,0.049860,unstable

In [136]:
a['stabf'].value_counts()

unstable    6380
stable      3620
Name: stabf, dtype: int64

In [137]:
a.shape

(10000, 14)

In [138]:
a.isna().sum()

tau1     0
tau2     0
tau3     0
tau4     0
p1       0
p2       0
p3       0
p4       0
g1       0
g2       0
g3       0
g4       0
stab     0
stabf    0
dtype: int64

In [139]:
a['stabf'].unique()

array(['unstable', 'stable'], dtype=object)

In [141]:
#In other to change 'stabf' to boolen values we replace stable with 1 and unstable with 0
a['stabf']=a['stabf'].replace({'stable':1, 'unstable': 0})

In [142]:
a.head(20)

,tau1,tau2,tau3,tau4,p1,p2,p3,p4,g1,g2,g3,g4,stab,stabf
0,2.959060,3.079885,8.381025,9.780754,3.763085,-0.782604,-1.257395,-1.723086,0.650456,0.859578,0.887445,0.958034,0.055347,0
1,9.304097,4.902524,3.047541,1.369357,5.067812,-1.940058,-1.872742,-1.255012,0.413441,0.862414,0.562139,0.781760,-0.005957,1
2,8.971707,8.848428,3.046479,1.214518,3.405158,-1.207456,-1.277210,-0.920492,0.163041,0.766689,0.839444,0.109853,0.003471,0
3,0.716415,7.669600,4.486641,2.340563,3.963791,-1.027473,-1.938944,-0.997374,0.446209,0.976744,0.929381,0.362718,0.028871,0
4,3.134112,7.608772,4.943759,9.857573,3.525811,-1.125531,-1.845975,-0.554305,0.797110,0.455450,0.656947,0.820923,0.049860,0
5,6.999209,9.109247,3.784066,4.267788,4.429669,-1.857139,-0.670397,-1.902133,0.261793,0.077930,0.542884,0.469931,-0.017385,1
6,6.710166,3.765204,6.929314,8.818562,2.397419,-0.614590,-1.208826,-0.574004,0.177890,0.397977,0.402046,0.376630,0.005954,0
7,6.953512,1.379125,5.719400,7.870307,3.224495,-0.748998,-1.186517,-1.288980,0.371385,0.633204,0.732741,0.380544,0.016634,0
8,4.689852,4.007747,1.478573,3.733787,4.041300,-1.410344,-1.238204,-1.392751,0.269708,0.250364,0.164941,0.482439,-0.038677,1
9,9.841496,1.413822,9.769856,7.641616,4.727595,-1.991363,-0.857637,-1.878594,0.376356,0.544415,0.792039,0.116263,0.012383,0
10,5.930110,6.730873,6.245138,0.533288,2.327092,-0.702501,-1.116920,-0.507671,0.239816,0.563110,0.164461,0.753701,-0.028411,1
11,5.381299,8.014521,8.095174,6.769248,5.507551,-1.972714,-1.849333,-1.685505,0.359974,0.173569,0.349144,0.628860,0.028130,0
12,1.616787,2.939228,0.819791,4.191804,3.752282,-1.484885,-1.280581,-0.986816,0.899698,0.866546,0.303921,0.077610,-0.048617,1
13,8.551598,8.314952,2.549964,9.926807,4.891714,-1.808626,-1.167061,-1.916026,0.612404,0.280983,0.354342,0.472192,0.027756,0
14,1.132108,2.920324,8.951079,7.248583,5.033681,-1.846080,-1.362777,-1.824824,0.352292,0.524173,0.599004,0.674390,0.014880,0
15,7.021362,4.374294,4.775904,8.838426,3.335857,-0.962392,-1.407627,-0.965839,0.711100,0.625364,0.468335,0.895143,0.072508,0
16,4.952241,8.088672,8.883319,5.694557,5.067296,-1.681414,-1.877061,-1.508820,0.305662,0.307904,0.889894,0.879428,0.065617,0
17,4.142830,2.439089,1.290456,9.456443,3.934796,-1.469299,-1.766941,-0.698556,0.800757,0.840807,0.917833,0.793982,-0.006966,1
18,9.346126,7.920030,2.335276,3.269181,4.581174,-1.106753,-1.747078,-1.727344,0.836076,0.713254,0.161518,0.515983,0.041374,0
19,3.931954,9.180890,6.064480,6.292147,5.363996,-1.695085,-1.880273,-1.788638,0.837264,0.611781,0.210692,0.697465,0.052781,0

In [147]:
scaler = MinMaxScaler()
scaler=scaler.fit(a)
df1=scaler.transform(a)

In [151]:
df2=pd.DataFrame(df1)
df2.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,0.258801,0.271561,0.829616,0.976978,0.509244,0.811642,0.495075,0.184572,0.632098,0.852229,0.881531,0.955894,0.715740,0.0
1,0.926793,0.463424,0.268117,0.091471,0.813957,0.039894,0.084809,0.496642,0.382588,0.855215,0.539078,0.770323,0.393359,1.0
2,0.891799,0.878795,0.268005,0.075171,0.425652,0.528367,0.481864,0.719670,0.118990,0.754440,0.831000,0.062980,0.442940,0.0
3,0.022700,0.754704,0.419623,0.193715,0.556118,0.648372,0.040670,0.668412,0.417084,0.975576,0.925677,0.329181,0.576507,0.0
4,0.277230,0.748301,0.467747,0.985065,0.453830,0.582991,0.102655,0.963811,0.786481,0.426782,0.638883,0.811553,0.686885,0.0

In [153]:
column_names={0:'tau1', 1:'tau2', 2:'tau3', 3:'tau4', 4:'p1', 5:'p2', 6:'p3', 7:'p4', 8:'g1', 9:'g2',
              10:'g3', 11:'g4', 12:'stab', 13:'stabf'}
df= df2.rename(columns=column_names)
df.head()

,tau1,tau2,tau3,tau4,p1,p2,p3,p4,g1,g2,g3,g4,stab,stabf
0,0.258801,0.271561,0.829616,0.976978,0.509244,0.811642,0.495075,0.184572,0.632098,0.852229,0.881531,0.955894,0.715740,0.0
1,0.926793,0.463424,0.268117,0.091471,0.813957,0.039894,0.084809,0.496642,0.382588,0.855215,0.539078,0.770323,0.393359,1.0
2,0.891799,0.878795,0.268005,0.075171,0.425652,0.528367,0.481864,0.719670,0.118990,0.754440,0.831000,0.062980,0.442940,0.0
3,0.022700,0.754704,0.419623,0.193715,0.556118,0.648372,0.040670,0.668412,0.417084,0.975576,0.925677,0.329181,0.576507,0.0
4,0.277230,0.748301,0.467747,0.985065,0.453830,0.582991,0.102655,0.963811,0.786481,0.426782,0.638883,0.811553,0.686885,0.0

In [154]:
# dropping the stab column
df=df.drop('stab', axis=1)

In [155]:
df.head(10)

,tau1,tau2,tau3,tau4,p1,p2,p3,p4,g1,g2,g3,g4,stabf
0,0.258801,0.271561,0.829616,0.976978,0.509244,0.811642,0.495075,0.184572,0.632098,0.852229,0.881531,0.955894,0.0
1,0.926793,0.463424,0.268117,0.091471,0.813957,0.039894,0.084809,0.496642,0.382588,0.855215,0.539078,0.770323,1.0
2,0.891799,0.878795,0.268005,0.075171,0.425652,0.528367,0.481864,0.719670,0.118990,0.754440,0.831000,0.062980,0.0
3,0.022700,0.754704,0.419623,0.193715,0.556118,0.648372,0.040670,0.668412,0.417084,0.975576,0.925677,0.329181,0.0
4,0.277230,0.748301,0.467747,0.985065,0.453830,0.582991,0.102655,0.963811,0.786481,0.426782,0.638883,0.811553,0.0
5,0.684139,0.906251,0.345657,0.396602,0.664921,0.095182,0.886441,0.065200,0.222947,0.029347,0.518808,0.442048,1.0
6,0.653709,0.343702,0.676782,0.875683,0.190299,0.923668,0.527457,0.950677,0.134621,0.366277,0.370546,0.343827,0.0
7,0.679328,0.092528,0.549405,0.775856,0.383459,0.834050,0.542331,0.473995,0.338316,0.613913,0.718672,0.347948,0.0
8,0.441015,0.369234,0.102939,0.340386,0.574220,0.393088,0.507870,0.404810,0.231280,0.210878,0.120943,0.455217,1.0
9,0.983369,0.096180,0.975829,0.751781,0.734501,0.005686,0.761603,0.080893,0.343549,0.520441,0.781097,0.069728,0.0

In [156]:
x=df.drop(['stabf'], axis=1)
y=df['stabf']

In [157]:
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

In [164]:
from sklearn.model_selection import train_test_split
x_train,x_valid,y_train,y_valid=train_test_split(x,y, test_size=0.2, random_state=1)
y_train.value_counts()

0.0    5092
1.0    2908
Name: stabf, dtype: int64

In [165]:
from sklearn.ensemble import ExtraTreesClassifier
from imblearn import under_sampling
import imblearn
from imblearn.over_sampling import SMOTE
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import recall_score, accuracy_score, precision_score, f1_score, confusion_matrix

In [166]:
import matplotlib.pyplot as plt
import seaborn as sns

# QUESTION 1

In [161]:
jam=ExtraTreesClassifier (max_features='auto', min_samples_leaf=6, min_samples_split=5)
jam.fit(x_train,y_train)
pred_jam=jam.predict(x_valid)
accuracy = accuracy_score(y_valid, pred_jam)
print(accuracy)

C:\Users\gyang.pam\New folder\lib\site-packages\sklearn\ensemble\_forest.py:427: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomForestClassifiers and ExtraTreesClassifiers.
  warn(

0.9165

# QUESTION 2

In [125]:
# Solving for Precision, Recall, and f1_score

TP= 255
TN=20
FP=1380
FN=45

Precision=TP/(TP+FP)
Recall=TP/(TP+FN)
f1_score=2*((Precision*Recall)/(Precision+Recall))

print(round(f1_score, 5))

0.26357

# QUESTION 14

In [77]:
# Random Forest 
from sklearn.ensemble import RandomForestClassifier
ran_f=RandomForestClassifier(random_state=1)
ran_f.fit(x_train, y_train)
ran_fpred=ran_f.predict(x_valid)
accuracy = accuracy_score(y_valid, ran_fpred)
print(accuracy)

0.9295

In [87]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import GradientBoostingClassifier, ExtraTreesClassifier

# QUESTION 15

In [162]:
# XGBoost
from xgboost import XGBClassifier
xg_b=XGBClassifier(random_state=1)
xg_b.fit(x_train, y_train)
xg_b_pred=xg_b.predict(x_valid)
accuracy = accuracy_score(y_valid, xg_b_pred)
print(accuracy)

0.9455

# QUESTION 16

In [163]:
# Light Gradient Boosting Machine
from lightgbm import LGBMClassifier
lgbm=LGBMClassifier(random_state=1)
lgbm.fit(x_train,y_train)
lgbm_pred=lgbm.predict(x_valid)
accuracy = accuracy_score(y_valid, lgbm_pred)
print(round(accuracy, 5 ))

0.9415